version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: zonesport_db
    restart: always
    environment:
      POSTGRES_USER: miki_user
      POSTGRES_PASSWORD: 7667
      POSTGRES_DB: zonesport_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: